# a cluster with 3 control-plane nodes and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  # Uncomment the below command to install CNI yourself
  #disableDefaultCNI: true
nodes:
- role: control-plane
- role: worker
- role: worker
