apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: logging-sidecar
  name: logging-sidecar
  namespace: baz
spec:
  containers:
  - image: busybox
    name: main
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo Logging data > /output/output.log; sleep 10;done"]
    volumeMounts:
    - name: vol1
      mountPath: /output


  - image: busybox
    name: sidecar
    command: ["/bin/sh"]
    args: ["-c", "tail -f  /input/output.log"]
    volumeMounts:
    - name: vol1
      mountPath: /input

  volumes:
  - name: vol1
    emptyDir: {}
